# Generated by Django 4.2.6 on 2023-10-25 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WareHouseA',
            fields=[
                ('UID', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('Product_Name', models.CharField(max_length=15)),
                ('quantity', models.IntegerField(default=0)),
                ('Time_In', models.DateTimeField(auto_now=True)),
                ('Time_Out', models.DateTimeField(blank=True)),
                ('destination', models.CharField(max_length=5)),
                ('status', models.CharField(default='In Storage', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='WareHouseB',
            fields=[
                ('UID', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('Product_Name', models.CharField(max_length=15)),
                ('quantity', models.IntegerField(default=0)),
                ('Time_In', models.DateTimeField(auto_now=True)),
                ('Time_Out', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='WareHouseC',
            fields=[
                ('UID', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('Product_Name', models.CharField(max_length=15)),
                ('quantity', models.IntegerField(default=0)),
                ('Time_In', models.DateTimeField(auto_now=True)),
                ('Time_Out', models.DateTimeField()),
            ],
        ),
    ]
